# Generated by Django 5.2.8 on 2025-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='Tags_name_66f2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='Tags_slug_f2305d_idx'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tags',
        ),
    ]
