"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from decouple import config
import os

REDIS_HOST = config("REDIS_HOST", default="127.0.0.1")
REDIS_PORT = config("REDIS_PORT", default=6379)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'unfold.contrib.forms',
    'unfold.contrib.filters',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd-party
    "rest_framework",
    'channels',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_celery_beat',
    'django_filters',
    'django_cleanup.apps.CleanupConfig',
    'silk',
    'ckeditor',
    'ckeditor_uploader',
    'storages',

    # local
    'apps.analytics',
    'apps.bookmarks',
    'apps.categories',
    'apps.comments',
    'apps.common',
    'apps.favourites',
    'apps.logs',
    'apps.notifications',
    'apps.posts',
    'apps.tags',
    'apps.users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'silk.middleware.SilkyMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    },
    # "replica": {
    #         "ENGINE": "django.db.backends.postgresql",
    #         "NAME": config("DB_NAME"),
    #         "USER": config("DB_USER"),
    #         "PASSWORD": config("DB_PASSWORD"),
    #         "HOST": config("DB_HOST"),
    #         "PORT": config("DB_PORT"),
    #     }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
    ("en", "English"),
    ("uz", "Uzbek"),
    ("ru", "Russian"),
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", "")
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", "")
AWS_PUBLIC_BUCKET_NAME = config("AWS_PUBLIC_BUCKET_NAME", "")
AWS_PRIVATE_BUCKET_NAME = config("AWS_PRIVATE_BUCKET_NAME", "")
AWS_S3_SIGNATURE_VERSION = "s3v4"

AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False  # generates signed URLS

STORAGES = {
    "default": {
        "BACKEND": "core.storages.PublicMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:5173",
    "http://13.53.73.97:8006",
    "http://13.53.73.97:8007",
    config("DOMAIN_URL"),
    config("FRONTEND_URL")
]

CORS_ORIGIN_WHITELIST = [
    "http://localhost:8080",
    "http://localhost:5173",
    "http://13.53.73.97:8006",
    "http://13.53.73.97:8007",
    config("DOMAIN_URL"),
    config("FRONTEND_URL")
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:5173",
    "http://13.53.73.97:8006",
    "http://13.53.73.97:8007",
    config("DOMAIN_URL"),
    config("FRONTEND_URL")
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_CREDENTIALS = True
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "rest_framework.permissions.IsAuthenticated",
    # ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",

    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "1500/min",
        "user": "30000/min",
    }
}
if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]
else:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer"
    ]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": (
        "rest_framework_simplejwt.authentication." "default_user_authentication_rule"
    ),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="email@example.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="password")

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "Asia/Tashkent"
CELERY_ENABLE_UTC = False
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 1800
CELERY_TASK_SOFT_TIME_LIMIT = 1200
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_CREATE_MISSING_QUEUES = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_COLOR = True
CELERYD_HIJACK_ROOT_LOGGER = False
CELERYD_LOG_COLOR = False
CELERY_TASK_SEND_SENT_EVENT = False

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {

}

SILKY_IGNORE_PATHS = [
    r'^static/',
    r'^media/',
]
SILKY_PYTHON_PROFILER_BINARY = False
SILKY_WARNINGS = False

SPECTACULAR_SETTINGS = {
    'TITLE': 'Blog Website API',
    'DESCRIPTION': 'Blog Website API',
    'VERSION': '1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}:{lineno} - {message}",
            "style": "{",
        },
    },

    "handlers": {
        "db": {
            "level": "INFO",
            "class": "apps.logs.handlers.DatabaseHandler",
            "formatter": "verbose",
        },

        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "app.log"),
            "formatter": "verbose",
        },

        "console": {
            "level": "WARNING",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console", "file", "db"],
        "level": "INFO",
    },

    "loggers": {
        "silk": {
            "handlers": [],
            "level": "CRITICAL",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file", "db"],
            "level": "ERROR",
            "propagate": False,
        },

        # Silence Celery worker INFO spam
        "celery": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },

        # Silence Celery worker strategy spam
        "celery.worker.strategy": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },

        # Silence Celery trace spam
        "celery.app.trace": {
            "handlers": [],
            "level": "ERROR",  # trace logs are extremely spammy
            "propagate": False,
        },

        # Silence Celery beat spam
        "celery.beat": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },

        # Silence Kombu (Celery's messaging layer)
        "kombu": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },

        # Silence AMQP logs
        "amqp": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },

        "apps.posts.tasks": {
            "handlers": ["console", "file", "db"],
            "level": "INFO",
            "propagate": False,
        },

    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
CKEDITOR_ALLOW_NONIMAGE_FILES = True
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 300,
        "width": "100%",
        "extraAllowedContent": "iframe[*];span[*];p[*];div[*];img[*]",
    }
}

SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]

GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET')

from django.templatetags.static import static
from django.urls import reverse

UNFOLD = {
    "SITE_TITLE": "Blog Post Admin",
    "SITE_HEADER": "Blog Administration",
    "SITE_URL": lambda request: reverse("admin:index"),
    "SITE_ICON": lambda request: static("icon.png"),

    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [
            # -------------------------
            # Content Management
            # -------------------------
            {
                "title": "Content Management",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Posts",
                        "icon": "description",
                        "link": lambda request: reverse("admin:posts_post_changelist"),
                    },
                    {
                        "title": "Categories",
                        "icon": "folder",
                        "link": lambda request: reverse("admin:categories_category_changelist"),
                    },
                ],
            },

            # -------------------------
            # User Management
            # -------------------------
            {
                "title": "User Management",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: reverse("admin:users_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": lambda request: reverse("admin:auth_group_changelist"),
                    },
                ],
            },

            # -------------------------
            # System
            # -------------------------
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "View Site",
                        "icon": "language",
                        "link": lambda request: reverse("admin:index"),
                    },
                ],
            },
        ],
    },

    # -----------------------------
    # TAB CONFIGURATION
    # -----------------------------
    "TABS": [
        {
            "models": ["posts.post"],
            "items": [
                {
                    "title": "All Posts",
                    "link": lambda request: reverse("admin:posts_post_changelist"),
                    "icon": "description",
                },
                {
                    "title": "Published",
                    "link": lambda request: reverse(
                        "admin:posts_post_changelist") + "?status__exact=published",
                    "icon": "check_circle",
                },
                {
                    "title": "Drafts",
                    "link": lambda request: reverse(
                        "admin:posts_post_changelist") + "?status__exact=draft",
                    "icon": "edit",
                },
            ],
        },

        {
            "models": ["users.user"],
            "items": [
                {
                    "title": "All Users",
                    "link": lambda request: reverse("admin:users_user_changelist"),
                    "icon": "people",
                },
                {
                    "title": "Active Users",
                    "link": lambda request: reverse(
                        "admin:users_user_changelist") + "?is_active__exact=1",
                    "icon": "check_circle",
                },
                {
                    "title": "Verified",
                    "link": lambda request: reverse(
                        "admin:users_user_changelist") + "?email_verified__exact=1",
                    "icon": "verified",
                },
            ],
        },
    ],

    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },

    "ENVIRONMENT": "development",

    "LOGIN": {
        "redirect_after": lambda request: reverse("admin:index"),
    },

    "SHOW_LANGUAGES": False,
    "SHOW_VIEW_ON_SITE": True,
}
