# Generated by Django 5.2.7 on 2025-10-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='PostImages',
        ),
    ]
