# Generated by Django 5.2.8 on 2025-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_reactiontype_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowed_reactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts_allowed', to='posts.reactiontype'),
        ),
    ]
