# Generated by Django 5.2.8 on 2025-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_allowed_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allowed_reactions',
            field=models.ManyToManyField(blank=True, related_name='posts_allowed', to='posts.reactiontype'),
        ),
    ]
