# Generated by Django 5.2.8 on 2025-11-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_allowed_reactions'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts_tags', to='tags.tag'),
        ),
    ]
