# Generated by Django 5.2.8 on 2025-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text formatted content', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Raw JSON formatted content'),
        ),
    ]
